<a href="https://colab.research.google.com/github/Harry2102/Harry2102/blob/main/Data_Processing_practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([85,498,2943,40,29,94,])
print(arr)
print(type(arr))


[  85  498 2943   40   29   94]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
print(np.__version__)


1.21.6


In [4]:
import numpy as np
arr = np.array((23,34,45,56,67.78))
print(arr)

[23.   34.   45.   56.   67.78]


In [8]:
import numpy as np
arr = np.array(42)
print(arr)


42


In [9]:
#1D array
import numpy as np
arr = np.array([45,34,23,12,21,24])
print(arr)

[45 34 23 12 21 24]


In [10]:
#2D array 
import numpy as np
arr = np.array([[51,43,23],[45,56,67]])
print(arr)

[[51 43 23]
 [45 56 67]]


In [12]:
#3D array 
import numpy as np 
arr = np.array([[[23,34,32],[45,56,67]],[[68,78,89],[22,33,44]]])
print(arr)

[[[23 34 32]
  [45 56 67]]

 [[68 78 89]
  [22 33 44]]]


In [15]:
a=np.array(44)
b=np.array([11,10,45,65,66,33])
c=np.array([[11,22,33],[44,55,66]])
d=np.array([[[100,200,300],[400,500,600]],[[900,800,700],[540,302,120]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [19]:
#two dimensional list to array
import numpy as np
data=[[11,12],[33,44],[55,66]]
data=np.array(data)
print(data)
print(type(data))

[[11 12]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [21]:
#define array
import numpy as np
data=np.array([10,20,30,40,50,60])#slice the values
print(data)
print(data[4])

[10 20 30 40 50 60]
50
